### ISSUE TITLE
Bad results in web interface and download not possible

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/ocr-fileformat#60]
The web interface (for example https://digi.bib.uni-mannheim.de/ocr-fileformat/) shows damaged results when converting from hOCR to ALTO2.0 or ALTO2.1:

    <?xml version="1.0" encoding="utf-8"?>
    <alto xmlns="http://www.loc.gov/standards˺lto/ns-v2#"
          xmlns:xlink="http://www.w3.org�/xlink"
          xmlns:xsi="http://www.w3.org�/XMLSchema-instance"
          xsi:schemaLocation="http://www.loc.gov/standards˺lto/ns-v2# http://www.loc.gov/standards˺lto/v2˺lto-2-0.xsd">
       <Description>
          <MeasurementUnit>pixel</MeasurementUnit>

It should look like this:

    <?xml version="1.0" encoding="utf-8"?>
    <alto xmlns="http://www.loc.gov/standards/alto/ns-v2#"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.loc.gov/standards/alto/ns-v2# http://www.loc.gov/standards/alto/v2/alto-2-0.xsd">
       <Description>
          <MeasurementUnit>pixel</MeasurementUnit>

It is also not possible to download the result using the `Download` button.

According to user feedback, the web interface worked two months ago. In the meantime, we have upgraded the server software from Debian Jessie to Stretch. So the problem might be related to the change from PHP‌ 5.6 to PHP 7.0

**Comment by zuphilip** [comment]
The encoding problem is also shown in the screenshot which was created a year ago and the Dockerfile was using PHP 7.0 from the beginning.

---

I only have found this code for the button, which will not save the original file if from url rather than the transformed one: https://github.com/UB-Mannheim/ocr-fileformat/blob/5ec0dd4f388fd3454489a627884d57062eb49447/web/ocr-fileformat.js#L86-L96.
