### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-fileformat#65]
(Splitted from #60)

## Current Behaviour

After uploading a local file and transform it, the download button does nothing.

After choosing an url of a file and transform it, the download button will simply provide a link to that url, which is the input file.

## Goal

The goal should be to download the output file. I guess that the button is currently more like a placeholder and the logic behind it is still missing.

## Code

I only have found this code for the button: https://github.com/UB-Mannheim/ocr-fileformat/blob/5ec0dd4f388fd3454489a627884d57062eb49447/web/ocr-fileformat.js#L86-L96.

**Comment by stweil** [comment]
Pull request #70 partially implemented the desired functionality. The following use case still does not work for me:

- Go to https://digi.bib.uni-mannheim.de/ocr-fileformat/
- Enter URL https://digi.bib.uni-mannheim.de/~stweil/ocr-praxis/0001-tesseract.hocr
- Transform from `hocr` to `alto2.0`
- Press 'Download' button

Expected behavior: download of result (ALTO XML)
Observed behavior: download of input (hOCR)

**Comment by zuphilip** [comment]
Yes, that is the else case in https://github.com/UB-Mannheim/ocr-fileformat/blob/b85360e094682b0d88953564c807fcbd5dcf668b/web/ocr-fileformat.js#L103-L105 . I agree that we don't need this and should just always do what is in the if case.

**Comment by kba** [comment]
Yup, and change the basename replacement. I'll send a PR.

**Comment by kba** [comment]
Also needs to make use of Blob/createObjectURL/revokeObjectURL since src attribute will become too large quickly.

**Comment by zuphilip** [comment]
It seems that #73 fixed this.

However, the behavior on digi is still different. @stweil Can you check that we have the latest version running?

**Comment by stweil** [comment]
We do now. Before that, a two years old version was running.
