### ISSUE TITLE
Name, description, link, relation

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-fileformat#9]
* Different names are used `ocr-transform` and `ocr-schemas`. I guess the latter is more general and would fit to the transformations as well as the validations. Should we change the name of this repo?
 * The description of the repo should be adjusted, e.g. `Validate and transform various OCR formats (hOCR, ALTO, PAGE, FineReader)`
 * I suggest to also add the link to our online interface. Okay?
 * The `hOCR-to-ALTO` is maybe now just one of several used style sheets. Should/Can we delete the relation as a fork and mention it among the others?

**Comment by kba** [comment]
>Different names are used ocr-transform and ocr-schemas. I guess the latter is more general and would fit to the transformations as well as the validations. Should we change the name of this repo?

I think `ocr-transform` is too narrow, that's why I changed it in my fork. But I didn't change it in the Makefile and other places so as not to break existing (un-)installation. `ocr-schemas` is possibly also too narrow. Maybe `ocr-formats` or `ocr-fileformat`?

> The description of the repo should be adjusted, e.g. Validate and transform various OCR formats (hOCR, ALTO, PAGE, FineReader)

Done, also for the README.

> I suggest to also add the link to our online interface. Okay?

Fine with me, I tried to prevent any kind of shell script injections by making the PHP script only communicate with the shell scripts via STDIN/STDOUT and validating input/output/schema against a fixed list. So apart from possible DOS attacks via sheer mass there should be no harm in making the app public.

> The hOCR-to-ALTO is maybe now just one of several used style sheets. Should/Can we delete the relation as a fork and mention it among the others?

That would be more in-line with the other approaches, true. If we were to do that, we should do so soon.
